name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Check code
      run:  sbt scalafmtCheck test:scalafmtCheck
    - name: Compile
      run: sbt clean compile
    - name: Test
      run: sbt test
    - name: Build docker image
      run: sbt 'service/docker:publishLocal'
    - name: Run end-to-end Test
      run:  sbt 'end-to-end/test'
    - name: Run dockerCompose
      run: sbt 'performance/dockerComposeUp'
    - name: Run performance test
      run: sbt 'performance/gatling:test'