name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Check code
      run:  sbt scalafmtCheck test:scalafmtCheck
    - name: Check dependencies
      run: sbt unusedCompileDependenciesTest
    - name: Compile
      run: sbt clean compile
    - name: Test
      run: sbt test
    - name: Build docker image
      run: sbt 'project service; set coverageEnabled := false; docker:publishLocal'
    - name: Run end-to-end Test
      run:  sbt 'project end-to-end; test'
    - name: Run dockerCompose
      run: sbt 'project performance; dockerComposeUp'
    - name: Run performance test
      run: sbt 'project performance; gatling:test'