name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check code
      run:  sbt scalafmtCheck test:scalafmtCheck
    - name: Check dependencies
      run: sbt unusedCompileDependenciesTest
    - name: Compile
      run: sbt clean coverage compile
    - name: Test
      run: sbt test
    - name: Check coverage
      run: sbt coverageReport
    - name: Build docker image
      run: sbt docker:publishLocal
    - name: Run end-to-end Test
      run:  sbt 'project end-to-end test'
